BEGIN;

CREATE TABLE "core_traineraccess" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "free_generation_used" boolean NOT NULL,
    "is_paid" boolean NOT NULL,
    "paid_until" date NULL,
    "payment_reference" varchar(100) NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "trainer_id" bigint NOT NULL UNIQUE
        REFERENCES "core_trainer" ("id")
        DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX "core_traineraccess_trainer_id_idx" ON "core_traineraccess" ("trainer_id");

-- Tell Django this migration is already applied, so `manage.py migrate`
-- won't try to (re)create this table later.
INSERT INTO "django_migrations" ("app", "name", "applied")
VALUES ('core', '0009_traineraccess', NOW());

COMMIT;
